"""Make award_level and award_type nullable

Revision ID: 660e21f121fd
Revises: fa6aa20ff71e
Create Date: 2025-11-14 09:51:39.335678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '660e21f121fd'
down_revision = 'fa6aa20ff71e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('award_level',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('award_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('award_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('award_level',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
