"""Make description field nullable

Revision ID: 86465b9ee894
Revises: 660e21f121fd
Create Date: 2025-11-14 13:58:39.009193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86465b9ee894'
down_revision = '660e21f121fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
