"""Add faculty_id, condition_expression, calculation_formula to rules and add RuleCondition/RuleCalculation tables

Revision ID: 1332141aaecf
Revises: 179aab6691cd
Create Date: 2025-12-05 09:10:44.280073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1332141aaecf'
down_revision = '179aab6691cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_calculation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('calculation_type', sa.String(length=50), nullable=True),
    sa.Column('formula', sa.String(length=200), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('precision', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_condition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('condition_type', sa.String(length=50), nullable=True),
    sa.Column('operator', sa.String(length=20), nullable=True),
    sa.Column('field', sa.String(length=100), nullable=True),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['rule_condition.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faculty_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('condition_expression', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('calculation_formula', sa.JSON(), nullable=True))
        batch_op.create_foreign_key(None, 'faculty', ['faculty_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('calculation_formula')
        batch_op.drop_column('condition_expression')
        batch_op.drop_column('faculty_id')

    op.drop_table('rule_condition')
    op.drop_table('rule_calculation')
    # ### end Alembic commands ###
