"""Add faculty score settings model

Revision ID: 179aab6691cd
Revises: 8019ea0dbefa
Create Date: 2025-12-04 09:44:03.271582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179aab6691cd'
down_revision = '8019ea0dbefa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty_score_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('academic_score_weight', sa.Float(), nullable=True),
    sa.Column('specialty_max_score', sa.Float(), nullable=True),
    sa.Column('performance_max_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faculty_id')
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_column('performance_max_score')
        batch_op.drop_column('specialty_max_score')
        batch_op.drop_column('academic_score_weight')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_score_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('specialty_max_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('performance_max_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    op.drop_table('faculty_score_settings')
    # ### end Alembic commands ###
