"""Add research_type, innovation_level, award_category, award_grade fields to application table

Revision ID: 23be26d2b8cd
Revises: f2e105602b9c
Create Date: 2025-12-06 11:19:22.461308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23be26d2b8cd'
down_revision = 'f2e105602b9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('research_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('innovation_level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('award_category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('award_grade', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('award_grade')
        batch_op.drop_column('award_category')
        batch_op.drop_column('innovation_level')
        batch_op.drop_column('research_type')

    # ### end Alembic commands ###
