"""Add parent_rule_id, link_type and linked_rules fields to Rule model

Revision ID: 25b8c2825bc8
Revises: 30f296b390e2
Create Date: 2025-12-05 13:24:23.343115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25b8c2825bc8'
down_revision = '30f296b390e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_rule_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('linked_rules', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('link_type', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(None, 'rule', ['parent_rule_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('link_type')
        batch_op.drop_column('linked_rules')
        batch_op.drop_column('parent_rule_id')

    # ### end Alembic commands ###
