"""Update tables to use department_id and major_id foreign keys instead of department and major strings

Revision ID: 2901d3ffb709
Revises: a2d222f5398b
Create Date: 2025-11-16 18:23:30.979731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2901d3ffb709'
down_revision = 'a2d222f5398b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('major_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'department', ['department_id'], ['id'])
        batch_op.create_foreign_key(None, 'major', ['major_id'], ['id'])
        batch_op.drop_column('department')
        batch_op.drop_column('major')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('major_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'department', ['department_id'], ['id'])
        batch_op.create_foreign_key(None, 'major', ['major_id'], ['id'])
        batch_op.drop_column('department')
        batch_op.drop_column('major')

    with op.batch_alter_table('student_evaluation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('major_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'major', ['major_id'], ['id'])
        batch_op.create_foreign_key(None, 'department', ['department_id'], ['id'])
        batch_op.drop_column('department')
        batch_op.drop_column('major')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faculty_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('major_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'major', ['major_id'], ['id'])
        batch_op.create_foreign_key(None, 'department', ['department_id'], ['id'])
        batch_op.create_foreign_key(None, 'faculty', ['faculty_id'], ['id'])
        batch_op.drop_column('department')
        batch_op.drop_column('major')
        batch_op.drop_column('faculty')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faculty', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('major', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('major_id')
        batch_op.drop_column('department_id')
        batch_op.drop_column('faculty_id')

    with op.batch_alter_table('student_evaluation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('major', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('major_id')
        batch_op.drop_column('department_id')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('major', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('major_id')
        batch_op.drop_column('department_id')

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('major', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('major_id')
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###
