"""Merge filename and original_filename fields in GraduateFile model

Revision ID: 2b4f9948cc7d
Revises: 30a76b04ddcb
Create Date: 2025-12-03 22:46:31.604074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b4f9948cc7d'
down_revision = '30a76b04ddcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graduate_file', schema=None) as batch_op:
        batch_op.drop_column('original_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graduate_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
