"""Remove unused fields from Application model

Revision ID: 2e2ab0dae2df
Revises: 573fb74d9ed4
Create Date: 2025-12-06 10:57:02.142257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e2ab0dae2df'
down_revision = '573fb74d9ed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('research_type')
        batch_op.drop_column('author_rank_type')
        batch_op.drop_column('innovation_role')
        batch_op.drop_column('innovation_level')
        batch_op.drop_column('team_role')
        batch_op.drop_column('performance_level')
        batch_op.drop_column('award_grade')
        batch_op.drop_column('author_order')
        batch_op.drop_column('performance_participation')
        batch_op.drop_column('award_category')
        batch_op.drop_column('performance_type')
        batch_op.drop_column('academic_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('performance_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('award_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('performance_participation', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('author_order', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('award_grade', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('performance_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('team_role', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('innovation_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('innovation_role', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('author_rank_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('research_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
