"""Remove is_special field from Rule model

Revision ID: 30f296b390e2
Revises: d222914e1ec1
Create Date: 2025-12-05 10:51:05.950046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f296b390e2'
down_revision = 'd222914e1ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.drop_column('is_special')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_special', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
