"""Add faculty foreign key to Application model

Revision ID: 349d223fcbfd
Revises: b802a6beedfa
Create Date: 2025-11-16 19:43:04.641609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '349d223fcbfd'
down_revision = 'b802a6beedfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faculty_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'faculty', ['faculty_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('faculty_id')

    # ### end Alembic commands ###
