"""Add one-to-one relationship between User and Student models and data synchronization

Revision ID: 3829db7ca4d3
Revises: 5551f97ba935
Create Date: 2025-11-17 18:25:11.653297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3829db7ca4d3'
down_revision = '5551f97ba935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['student_id'])
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['student_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
