"""Remove rule inheritance, association, and condition_expression fields

Revision ID: 3e33cf95eba6
Revises: 25b8c2825bc8
Create Date: 2025-12-05 16:26:32.201497

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e33cf95eba6'
down_revision = '25b8c2825bc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule_condition')
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('rule_parent_rule_id_fkey'), type_='foreignkey')
        batch_op.drop_column('linked_rules')
        batch_op.drop_column('condition_expression')
        batch_op.drop_column('parent_rule_id')
        batch_op.drop_column('link_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('parent_rule_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('condition_expression', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('linked_rules', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('rule_parent_rule_id_fkey'), 'rule', ['parent_rule_id'], ['id'])

    op.create_table('rule_condition',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('condition_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('operator', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('field', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('value', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['rule_condition.id'], name=op.f('rule_condition_parent_id_fkey')),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], name=op.f('rule_condition_rule_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('rule_condition_pkey'))
    )
    # ### end Alembic commands ###
