"""Remove PerformanceDetail model

Revision ID: 43d027e057c8
Revises: 3829db7ca4d3
Create Date: 2025-11-18 12:11:04.892911

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '43d027e057c8'
down_revision = '3829db7ca4d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performance_detail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_detail',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('rule_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('project_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('award_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('award_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('award_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('author_order', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('self_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('score_basis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('approved_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], name=op.f('performance_detail_rule_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], name=op.f('performance_detail_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('performance_detail_pkey'))
    )
    # ### end Alembic commands ###
