"""Allow self_score, faculty_id, and award_date to be null for draft applications

Revision ID: 5551f97ba935
Revises: 349d223fcbfd
Create Date: 2025-11-17 12:23:03.813207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5551f97ba935'
down_revision = '349d223fcbfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('faculty_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('self_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('award_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('award_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('self_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('faculty_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
