"""Add dynamic_coefficients field to Application model

Revision ID: 573fb74d9ed4
Revises: b8c331b13927
Create Date: 2025-12-06 10:47:51.244977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573fb74d9ed4'
down_revision = 'b8c331b13927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dynamic_coefficients', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('dynamic_coefficients')

    # ### end Alembic commands ###
