"""Add avatar file size limit to system settings

Revision ID: 668a298c70ab
Revises: d12f26328eba
Create Date: 2025-12-03 19:06:39.323996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '668a298c70ab'
down_revision = 'd12f26328eba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_file_size_limit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_column('avatar_file_size_limit')

    # ### end Alembic commands ###
