"""Add user_identifier to Captcha

Revision ID: 6be17e8f4f8a
Revises: afbe0128fce2
Create Date: 2025-12-10 16:36:17.814002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6be17e8f4f8a'
down_revision = 'afbe0128fce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'rule', ['rule_id'], ['id'])
        batch_op.create_foreign_key(None, 'faculty', ['faculty_id'], ['id'])
        batch_op.create_foreign_key(None, 'department', ['department_id'], ['id'])
        batch_op.create_foreign_key(None, 'major', ['major_id'], ['id'])
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['student_id'])

    with op.batch_alter_table('captcha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_identifier', sa.String(length=100), nullable=False))
        batch_op.create_index(batch_op.f('ix_captcha_user_identifier'), ['user_identifier'], unique=False)

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'faculty', ['faculty_id'], ['id'])

    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('faculty_score_settings', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['faculty_id'])
        batch_op.create_foreign_key(None, 'faculty', ['faculty_id'], ['id'])

    with op.batch_alter_table('graduate_file', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'faculty', ['faculty_id'], ['id'])

    with op.batch_alter_table('major', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'department', ['department_id'], ['id'])

    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'faculty', ['faculty_id'], ['id'])

    with op.batch_alter_table('rule_calculation', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'rule', ['rule_id'], ['id'])

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['student_id'])
        batch_op.create_foreign_key(None, 'major', ['major_id'], ['id'])
        batch_op.create_foreign_key(None, 'department', ['department_id'], ['id'])
        batch_op.create_foreign_key(None, 'faculty', ['faculty_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['student_id'])
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_foreign_key(None, 'department', ['department_id'], ['id'])
        batch_op.create_foreign_key(None, 'faculty', ['faculty_id'], ['id'])
        batch_op.create_foreign_key(None, 'major', ['major_id'], ['id'])
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['student_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('rule_calculation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('major', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('graduate_file', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('faculty_score_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('captcha', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_captcha_user_identifier'))
        batch_op.drop_column('user_identifier')

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
