"""Update file size limits

Revision ID: 6e845fbaf35f
Revises: f2ac5e1c441c
Create Date: 2025-11-18 22:22:49.707239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e845fbaf35f'
down_revision = 'f2ac5e1c441c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('single_file_size_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_file_size_limit', sa.Integer(), nullable=True))
        batch_op.drop_column('file_size_limit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_size_limit', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('total_file_size_limit')
        batch_op.drop_column('single_file_size_limit')

    # ### end Alembic commands ###
