"""Remove level, grade, category, participation_type fields from Rule model

Revision ID: 8f06390ffc40
Revises: 1332141aaecf
Create Date: 2025-12-05 09:33:59.226962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f06390ffc40'
down_revision = '1332141aaecf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.drop_column('level')
        batch_op.drop_column('category')
        batch_op.drop_column('participation_type')
        batch_op.drop_column('grade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('participation_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
