"""Remove unused fields: research_type, innovation_level, award_category, award_grade from application table

Revision ID: 90f97febfb61
Revises: 23be26d2b8cd
Create Date: 2025-12-06 11:23:14.918862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90f97febfb61'
down_revision = '23be26d2b8cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('award_category')
        batch_op.drop_column('innovation_level')
        batch_op.drop_column('research_type')
        batch_op.drop_column('award_grade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('award_grade', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('research_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('innovation_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('award_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
