"""Add Captcha model

Revision ID: afbe0128fce2
Revises: 90f97febfb61
Create Date: 2025-12-10 16:03:53.552188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afbe0128fce2'
down_revision = '90f97febfb61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captcha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('text', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('captcha', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_captcha_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('captcha', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_captcha_token'))

    op.drop_table('captcha')
    # ### end Alembic commands ###
