"""Merge Student and StudentEvaluation models, create PerformanceDetail model, add faculty_id to Student

Revision ID: b802a6beedfa
Revises: e8b644505265
Create Date: 2025-11-16 19:30:13.294874

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b802a6beedfa'
down_revision = 'e8b644505265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('award_date', sa.Date(), nullable=False),
    sa.Column('award_level', sa.String(length=50), nullable=True),
    sa.Column('award_type', sa.String(length=50), nullable=True),
    sa.Column('author_order', sa.String(length=20), nullable=True),
    sa.Column('self_score', sa.Float(), nullable=False),
    sa.Column('score_basis', sa.Text(), nullable=True),
    sa.Column('approved_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('comprehensive_performance_detail')
    op.drop_table('academic_specialty_detail')
    op.drop_table('student_evaluation')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faculty_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('academic_specialty_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('comprehensive_performance_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('comprehensive_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('major_ranking', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'faculty', ['faculty_id'], ['id'])
        batch_op.drop_column('ranking')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ranking', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('major_ranking')
        batch_op.drop_column('comprehensive_score')
        batch_op.drop_column('total_score')
        batch_op.drop_column('comprehensive_performance_total')
        batch_op.drop_column('academic_specialty_total')
        batch_op.drop_column('faculty_id')

    op.create_table('student_evaluation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('student_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('cet4_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cet6_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('academic_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('academic_weighted', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('academic_specialty_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('comprehensive_performance_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('comprehensive_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('major_ranking', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_students', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('major_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('student_evaluation_department_id_fkey')),
    sa.ForeignKeyConstraint(['major_id'], ['major.id'], name=op.f('student_evaluation_major_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('student_evaluation_pkey')),
    sa.UniqueConstraint('student_id', name=op.f('student_evaluation_student_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('academic_specialty_detail',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('project_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('award_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('award_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('award_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('author_order', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('self_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('score_basis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('approved_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('rule_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], name=op.f('academic_specialty_detail_rule_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], name=op.f('academic_specialty_detail_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('academic_specialty_detail_pkey'))
    )
    op.create_table('comprehensive_performance_detail',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('project_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('award_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('award_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('award_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('author_order', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('self_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('score_basis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('approved_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('rule_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], name=op.f('comprehensive_performance_detail_rule_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], name=op.f('comprehensive_performance_detail_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('comprehensive_performance_detail_pkey'))
    )
    op.drop_table('performance_detail')
    # ### end Alembic commands ###
