"""Remove team_role, author_rank_type, author_rank, author_rank_ratio fields from Rule model

Revision ID: d222914e1ec1
Revises: 8f06390ffc40
Create Date: 2025-12-05 09:48:31.545496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd222914e1ec1'
down_revision = '8f06390ffc40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.drop_column('author_rank')
        batch_op.drop_column('author_rank_type')
        batch_op.drop_column('author_rank_ratio')
        batch_op.drop_column('team_role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_role', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('author_rank_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('author_rank_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('author_rank', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
