"""Update SystemSettings fields to max_score

Revision ID: d73927ab8c47
Revises: d9a01d4867fd
Create Date: 2025-11-18 21:31:32.005076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd73927ab8c47'
down_revision = 'd9a01d4867fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty_max_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('performance_max_score', sa.Float(), nullable=True))
        batch_op.drop_column('performance_score_weight')
        batch_op.drop_column('specialty_score_weight')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty_score_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('performance_score_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('performance_max_score')
        batch_op.drop_column('specialty_max_score')

    # ### end Alembic commands ###
