"""Add SystemSettings table

Revision ID: d9a01d4867fd
Revises: a68419f7fd8a
Create Date: 2025-11-18 19:03:36.872876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9a01d4867fd'
down_revision = 'a68419f7fd8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=10), nullable=True),
    sa.Column('application_start', sa.Date(), nullable=True),
    sa.Column('application_end', sa.Date(), nullable=True),
    sa.Column('file_size_limit', sa.Integer(), nullable=True),
    sa.Column('allowed_file_types', sa.String(length=200), nullable=True),
    sa.Column('academic_score_weight', sa.Float(), nullable=True),
    sa.Column('specialty_score_weight', sa.Float(), nullable=True),
    sa.Column('performance_score_weight', sa.Float(), nullable=True),
    sa.Column('system_status', sa.String(length=20), nullable=True),
    sa.Column('last_backup', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    # ### end Alembic commands ###
