"""Add foreign key constraints for all models

Revision ID: e8b644505265
Revises: f561fa59ad19
Create Date: 2025-11-16 18:46:12.221475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8b644505265'
down_revision = 'f561fa59ad19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_specialty_detail', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['student_id'])

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('major_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['student_id'])

    with op.batch_alter_table('comprehensive_performance_detail', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['student_id'])

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('major_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('student_evaluation', schema=None) as batch_op:
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('major_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_evaluation', schema=None) as batch_op:
        batch_op.alter_column('major_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('major_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('comprehensive_performance_detail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('major_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('academic_specialty_detail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
