"""Remove award_level and award_type fields from Application model

Revision ID: f2e105602b9c
Revises: 2e2ab0dae2df
Create Date: 2025-12-06 11:00:15.813250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e105602b9c'
down_revision = '2e2ab0dae2df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('award_level')
        batch_op.drop_column('award_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('award_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('award_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
