"""Add foreign key relationships for all models

Revision ID: f561fa59ad19
Revises: 2901d3ffb709
Create Date: 2025-11-16 18:30:59.377236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f561fa59ad19'
down_revision = '2901d3ffb709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_specialty_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rule_id', sa.Integer(), nullable=True))
        # 暂时不创建外键约束，因为已有记录的student_id在student表中不存在
        # batch_op.create_foreign_key(None, 'student', ['student_id'], ['student_id'])
        batch_op.create_foreign_key(None, 'rule', ['rule_id'], ['id'])

    with op.batch_alter_table('application', schema=None) as batch_op:
        # 暂时不设置为NOT NULL，因为已有记录可能包含NULL值
        # batch_op.alter_column('department_id',
        #        existing_type=sa.INTEGER(),
        #        nullable=False)
        # batch_op.alter_column('major_id',
        #        existing_type=sa.INTEGER(),
        #        nullable=False)
        # 暂时不创建外键约束，因为已有记录的student_id在student表中不存在
        # batch_op.create_foreign_key(None, 'student', ['student_id'], ['student_id'])
        pass

    with op.batch_alter_table('comprehensive_performance_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rule_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'rule', ['rule_id'], ['id'])
        # 暂时不创建外键约束，因为已有记录的student_id在student表中不存在
        # batch_op.create_foreign_key(None, 'student', ['student_id'], ['student_id'])

    with op.batch_alter_table('student', schema=None) as batch_op:
        # 暂时不设置为NOT NULL，因为已有记录可能包含NULL值
        # batch_op.alter_column('department_id',
        #        existing_type=sa.INTEGER(),
        #        nullable=False)
        # batch_op.alter_column('major_id',
        #        existing_type=sa.INTEGER(),
        #        nullable=False)
        pass

    with op.batch_alter_table('student_evaluation', schema=None) as batch_op:
        # 暂时不设置为NOT NULL，因为已有记录可能包含NULL值
        # batch_op.alter_column('department_id',
        #        existing_type=sa.INTEGER(),
        #        nullable=False)
        # batch_op.alter_column('major_id',
        #        existing_type=sa.INTEGER(),
        #        nullable=False)
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_evaluation', schema=None) as batch_op:
        batch_op.alter_column('major_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('major_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('comprehensive_performance_detail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rule_id')

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('major_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('academic_specialty_detail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rule_id')

    # ### end Alembic commands ###
