"""Update Rule model: make level nullable and add research_type field

Revision ID: f7bee6350526
Revises: e68f1999335a
Create Date: 2025-11-16 12:04:24.839547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7bee6350526'
down_revision = 'e68f1999335a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('research_type', sa.String(length=50), nullable=True))
        batch_op.alter_column('level',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.alter_column('level',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('research_type')

    # ### end Alembic commands ###
