"""Update application table

Revision ID: fa6aa20ff71e
Revises: a0f26c3ea064
Create Date: 2025-11-14 08:59:52.837770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6aa20ff71e'
down_revision = 'a0f26c3ea064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('research_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('innovation_level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('innovation_role', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('award_grade', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('award_category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('author_rank_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('author_order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('performance_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('performance_level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('performance_participation', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('team_role', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('team_role')
        batch_op.drop_column('performance_participation')
        batch_op.drop_column('performance_level')
        batch_op.drop_column('performance_type')
        batch_op.drop_column('author_order')
        batch_op.drop_column('author_rank_type')
        batch_op.drop_column('award_category')
        batch_op.drop_column('award_grade')
        batch_op.drop_column('innovation_role')
        batch_op.drop_column('innovation_level')
        batch_op.drop_column('research_type')
        batch_op.drop_column('academic_type')

    # ### end Alembic commands ###
