"""Add author_rank_ratio, max_score, max_count, is_special to Rule model

Revision ID: febb34758600
Revises: f7bee6350526
Create Date: 2025-11-16 12:25:22.687275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'febb34758600'
down_revision = 'f7bee6350526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_rank_ratio', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_special', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.drop_column('is_special')
        batch_op.drop_column('max_count')
        batch_op.drop_column('max_score')
        batch_op.drop_column('author_rank_ratio')

    # ### end Alembic commands ###
